### ISSUE TITLE
Build Repository for Campus Activities

### ISSUE THREAD

**Issue by vishakh-abhayan** [gtech-mulearn/mucampus-events#3]
**Description:**
This repository is designed for campuses to submit proof of work for their conducted activities, referred to as "Campus Karma." The submission will include event photos, participant MU IDs, faculty MU IDs, enabler MU IDs, and their names. Additionally, campuses can submit details of their learning circle-based activities. The repository will be built using Jekyll, and campus leads will need to edit markdown files as per the provided template. Karma points will be automatically updated with GitHub Actions using the provided MU IDs.

**Goals:**
1. Create a Jekyll-based repository for campuses to submit activity proof.
2. Enable automatic updates of karma points using GitHub Actions.
3. Ensure easy editing of markdown files by campus leads.
4. Facilitate the inclusion of event photos and MU IDs for participants, faculty, and enablers.

**Expected Outcomes:**
1. A functional Jekyll site that campuses can use to submit activities.
2. Templates for markdown files that campuses can easily edit.
3. Automated karma point updates via GitHub Actions.
4. A user-friendly interface for submitting event photos and MU IDs.

**Acceptance Criteria:**
1. **Jekyll Setup:**
   - The repository is correctly set up with Jekyll.
   - The site structure supports easy navigation and submission of activities.
2. **Markdown Templates:**
   - Templates are provided for campuses to submit their activities.
   - Templates include fields for event photos, participant MU IDs, faculty MU IDs, enabler MU IDs, and names.
3. **GitHub Actions:**
   - GitHub Actions are configured to automatically update karma points based on submitted MU IDs.
   - The process is tested and verified to work correctly.
4. **User Interface:**
   - Clear instructions are provided for campus leads on how to edit and submit markdown files.
   - The submission process is tested to ensure it is user-friendly and error-free.

**Implementation Details:**
1. **Repository Setup:**
   - Initialize a new Jekyll site.
   - Set up the directory structure for markdown submissions.
2. **Template Creation:**
   - Design and create markdown templates for activity submissions.
   - Ensure templates are easy to understand and fill out.
3. **GitHub Actions:**
   - Write scripts for GitHub Actions to process submitted markdown files.
   - Implement logic to update karma points based on MU IDs.
4. **Documentation:**
   - Provide detailed documentation on how to use the repository.
   - Include examples and FAQs to assist campus leads.
   
   
 **Necessary Tech Skills:** Jekyll, Markdown, GitHub Actions, HTML/CSS

**Mentor Tags:** @rejahrehim 

**Complexity:** Medium

**Relevant Categories:** Community, Automation, Web Development

---

**Links to Mockups/Wireframes:** *(Include links if available)*

---

If there are any additional details or modifications needed, please let me know!

**Comment by Jenin82** [comment]
@vishakh-abhayan What is the current status for this ?

**Comment by vishakh-abhayan** [comment]
> [@vishakh-abhayan](https://github.com/vishakh-abhayan) What is the current status for this ?

am currently building a Jekyll  theme for this

**Comment by Jenin82** [comment]
@Ansanjohny test this out

**Comment by vishakh-abhayan** [comment]
@rejahrehim @Jenin82 @Ansanjohny 
 https://gtech-mulearn.github.io/mucampus-events/
